// _________________________________________
//🅼🅻🆃🅵🆇
//@version=5

// _________________________________________
indicator(title            ='𝙏𝙊𝙊𝙇𝙆𝙄𝙏 𝙎𝙈𝙊𝙊𝙏𝙃𝙀𝘿 𝙀𝙈𝘼 𝙑.1 🅼🅻🆃🅵🆇', overlay=true)

///COLOR TYPE _________________________________________
dark                       = #131722
white                      = #c4d3ff
green                      = #179c74
purple                     = #7034ff
gray                       = #394669
red                        = #e91e63
orange                     = #e65100
blue                       = #2962ff
Transparent_Color          = color.new(color.new(white,0), 100)

//COLOR TYPE THEME _________________________________________
color_theme                = input.string(defval="𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀", title=" 𝙎𝙀𝙇𝙀𝘾𝙏 𝘾𝙊𝙇𝙊𝙍 𝙏𝙃𝙀𝙈𝙀", options=["𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀", "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎","𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀", "𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" , "𝘿𝘼𝙍𝙆 𝙀𝙂𝙂 𝙔𝙊𝙇𝙆 𝙏𝙃𝙀𝙈𝙀","𝘽𝙇𝙐𝙀 𝙒𝙃𝙄𝙏𝙀"])
show_plot_candle           = input.bool(defval = true , title   ="  𝙎𝙃𝙊𝙒 𝙋𝙇𝙊𝙏 𝘾𝘼𝙉𝘿𝙇𝙀")

// COLOR BASED ON THEME
white_col                  = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? white : color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? white : color_theme =="𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? white : color_theme == "𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? white : color_theme == "𝘿𝘼𝙍𝙆 𝙀𝙂𝙂 𝙔𝙊𝙇𝙆 𝙏𝙃𝙀𝙈𝙀" ? white : white
dark_col                   = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? dark : color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? dark : color_theme =="𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? dark : color_theme == "𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? gray : color_theme == "𝘿𝘼𝙍𝙆 𝙀𝙂𝙂 𝙔𝙊𝙇𝙆 𝙏𝙃𝙀𝙈𝙀" ? gray : gray
col_bull                   = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? white: color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? purple : color_theme =="𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? green : color_theme == "𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? green : color_theme == "𝘿𝘼𝙍𝙆 𝙀𝙂𝙂 𝙔𝙊𝙇𝙆 𝙏𝙃𝙀𝙈𝙀" ? orange : blue
col_bear                   = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? white: color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? green : color_theme =="𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? red : color_theme == "𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? gray  : color_theme == "𝘿𝘼𝙍𝙆 𝙀𝙂𝙂 𝙔𝙊𝙇𝙆 𝙏𝙃𝙀𝙈𝙀" ? gray : white
col_bear2                  = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? gray: color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? green : color_theme =="𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? red : color_theme == "𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? gray : color_theme == "𝘿𝘼𝙍𝙆 𝙀𝙂𝙂 𝙔𝙊𝙇𝙆 𝙏𝙃𝙀𝙈𝙀" ? gray : white
box_col_bull               = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? color.new(white,70): color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? color.new(purple,70) : color_theme == "𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? color.new(green,70): color_theme =="𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? color.new(green,70) : color_theme =="𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? color.new(orange,70) :  color.new(blue,70)
box_col_bear               = color_theme == "𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? color.new(gray,70): color_theme == "𝙈𝙇𝙏𝙁𝙓 𝙏𝙃𝙀𝙈𝙀𝙎" ? color.new(green,70) : color_theme == "𝙎𝙏𝘼𝙉𝘿𝘼𝙍𝘿 𝘿𝘼𝙍𝙆 𝙏𝙃𝙀𝙈𝙀" ? color.new(red,70): color_theme =="𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ? color.new(gray,70) : color_theme =="𝘿𝘼𝙍𝙆 𝙄𝘾𝙏 𝙏𝙃𝙀𝙈𝙀" ?  color.new(gray,70) : color.new(white,70)

// _________________________________________
//              𝙀𝙈𝘼 𝙍𝙄𝘽𝘽𝙊𝙉 V.1
// _________________________________________
// EMA RIBON SETTINGS ____________________________________________________________________
ema1_s                     = 4
ema2_s                     = 5
trend                      = 200
// SMOOTHING FUNCTION TO REDUCE PLOT ROUGHNESS FOR EMA RIBON ____________________________________________________________________
smooth(src, length) =>
    ta.ema(ta.ema(ta.ema(src, length), length), length)

// CALCULATING SMOOTHED EMA RIBON ____________________________________________________________________
ema_s1                     = smooth(close, ema1_s)
ema_s2                     = smooth(close, ema2_s)
ema_close                 = ta.sma(close,1)

ema_trend                  = ta.sma(close,trend)
emaup_trend                = ema_s1 >= ema_s2
emadown_trend              = ema_s1 <= ema_s2
color_trend                = ema_s2 >= ema_trend
// PLOTTING EMA LINES WITH SMOOTHING AND COLOR TRANSITION ____________________________________________________________________
plotema_close              = plot(ema_close, title="𝙎𝙈𝙊𝙊𝙏𝙃𝙀𝘿 𝙀𝙈𝘼 CLOSE", color= emaup_trend ? color.new(col_bull, 0) : emadown_trend ? color.new(col_bear2, 0) : na , linewidth=1)
plotema1_s_                = plot(ema_s1, title="𝙎𝙈𝙊𝙊𝙏𝙃𝙀𝘿 𝙀𝙈𝘼 1", color= emaup_trend ? color.new(col_bull, 0) : emadown_trend ? color.new(col_bear2, 0) : na , linewidth=1)
plotema2_s_                = plot(ema_s2, title="𝙎𝙈𝙊𝙊𝙏𝙃𝙀𝘿 𝙀𝙈𝘼 2", color= emaup_trend ? color.new(col_bull, 0) : emadown_trend ? color.new(col_bear2, 0) : na , linewidth=1)
plotema_trend              = plot(ema_trend, title="𝙎𝙈𝙊𝙊𝙏𝙃𝙀𝘿 𝙀𝙈𝘼", color= color_trend ? color.new(col_bull, 0) : color.new(col_bear2, 0) , linewidth=3)

// FILL BETWEEN EMAS FOR VISUAL CLARITY ____________________________________________________________________
fill(plotema1_s_, plotema2_s_, color= emaup_trend ? color.new(col_bull, 70) : emadown_trend ? color.new(col_bear2, 70) : na)
fill(plotema_close, plotema2_s_, color= emaup_trend ? color.new(col_bull, 70) : emadown_trend ? color.new(col_bear2, 70) : na)

// TREND CONDITIONS


// SUPPLY AND DEMAND CONDITIONS ____________________________________________________________________
demand                     = ta.crossover(close[1], high[2])
supply                     = ta.crossunder(close[1], low[2])

// LABELS SUPPLY AND DEMAND ____________________________________________________________________
var label[] buy_label      = array.new_label()
var label[] sell_label     = array.new_label()

//BUY AND SELL CONDITIONS
buy_conditions_1           = demand and  ema_s2 >= ema_trend and low[1] <= ema_trend
buy_conditions_2           = demand and  ema_s2 >= ema_trend and low[2] <= ema_trend
buy_conditions_3           = demand and  ema_s2 >= ema_trend and low[3] <= ema_trend

sell_conditions_1          = supply and  ema_s2 <= ema_trend and high[1] >= ema_trend
sell_conditions_2          = supply and  ema_s2 <= ema_trend and high[2] >= ema_trend
sell_conditions_3          = supply and  ema_s2 <= ema_trend and high[3] >= ema_trend

if buy_conditions_1 or buy_conditions_2  or buy_conditions_3
    buy_l                  = label.new(bar_index[1],low[1],'𝘽𝙐𝙔',size = size.tiny,yloc = yloc.price,textcolor = #000000,color =white_col,style = label.style_label_up)
    array.push(buy_label,buy_l)

if sell_conditions_1 or sell_conditions_2  or sell_conditions_3 
    sell_l                 = label.new(bar_index[1],high[1],'𝙎𝙀𝙇𝙇 ',size = size.tiny,yloc = yloc.price,textcolor = #000000,color =white_col,style = label.style_label_down )
    array.push(sell_label,sell_l)

// ALERT BUY AND SELL CONDITIONS ____________________________________________________________________
alertcondition(buy_conditions_1 or buy_conditions_2  or buy_conditions_3, title="𝘽𝙐𝙔 𝘾𝙊𝙉𝘿𝙄𝙏𝙄𝙊𝙉 𝘾𝙍𝙀𝘼𝙏𝙀𝘿", message="𝘽𝙐𝙔 𝘾𝙊𝙉𝘿𝙄𝙏𝙄𝙊𝙉 𝘾𝙍𝙀𝘼𝙏𝙀𝘿")
alertcondition(sell_conditions_1 or sell_conditions_2 or sell_conditions_3, title="𝙎𝙀𝙇𝙇 𝘾𝙊𝙉𝘿𝙄𝙏𝙄𝙊𝙉 𝘾𝙍𝙀𝘼𝙏𝙀𝘿", message="𝙎𝙀𝙇𝙇 𝘾𝙊𝙉𝘿𝙄𝙏𝙄𝙊𝙉 𝘾𝙍𝙀𝘼𝙏𝙀𝘿")

// _________________________________________
//       𝙎𝙉𝙍 𝙒𝙄𝙏𝙃 𝘽𝙍𝙀𝘼𝙆𝙀𝙍 𝙇𝙄𝙉𝙀𝙎 V.1
// _________________________________________
show_snr                  = input.bool(false,'𝙎𝙃𝙊𝙒 𝙎𝙉𝙍 ')

// INPUTS PARAMETERS _________________________________________
length                    = 40
src                       = close

// CALCULATE SNR LEVELS _________________________________________
support                   = ta.lowest(low, length)
resistance                = ta.highest(high, length)

// CREATE SNR LINES  _________________________________________
var line supportLine      = na
var line resistanceLine   = na

if show_snr and (ema_s1 >= ema_s2  and close[1] <= ema_s1)
    resistanceLine       := line.new(bar_index - (length / 2) , resistance, bar_index + length, resistance, xloc=xloc.bar_index, color=col_bull, width=2)

if  show_snr and ( ema_s1 <= ema_s2 and close[1] >= ema_s1)
    supportLine          := line.new(bar_index - (length / 2) , support, bar_index + length, support, xloc=xloc.bar_index, color=col_bear2, width=2)

// _________________________________________
//             𝙈𝙏𝙁 𝙁𝙑𝙂 V.1
// _________________________________________
// GENERAL FVG SETTINGS _________________________________________
changelvl                     = true
changecolor                   = true
extend_r                      = input.bool(false, "𝙀𝙓𝙏𝙀𝙉𝘿 𝘽𝙊𝙓𝙀𝙎 𝙁𝙑𝙂 𝙏𝙊 𝙏𝙃𝙀 𝙍𝙄𝙂𝙃𝙏", group='𝙂𝙀𝙉𝙀𝙍𝘼𝙇 𝙁𝙑𝙂')
max_boxes                     = 4

// STYLE SETTINGS _________________________________________
plotLabel                     = true
LabelColor                    = white_col
LabelSize                     = size.tiny
BullColor                     = box_col_bull
BearColor                     = box_col_bear
BullColorTested               = input.color(color.new(color.blue,50),'𝙒𝙃𝙀𝙉 𝙁𝙑𝙂 𝙈𝙄𝙏𝙄𝙂𝘼𝙏𝙄𝙊𝙉',group = '𝙂𝙀𝙉𝙀𝙍𝘼𝙇 𝙁𝙑𝙂')
BearColorTested               = BullColorTested

// FLEXIBLE TIMEFRAME INPUT _________________________________________
tf1                           = input.timeframe("", "𝙏𝙄𝙈𝙀𝙁𝙍𝘼𝙈𝙀 𝙁𝙑𝙂", group='𝙂𝙀𝙉𝙀𝙍𝘼𝙇 𝙁𝙑𝙂')
tf2                           = '15'
tf3                           = '240'
show_tf1                      = input.bool(defval = false , title   ="𝙎𝙃𝙊𝙒 𝙁𝙑𝙂 ",group = '𝙂𝙀𝙉𝙀𝙍𝘼𝙇 𝙁𝙑𝙂')
show_tf2                      = false
show_tf3                      = false

// VARIABLES FOR STORING BOXES _________________________________________
var box[] bull_box            = array.new_box()
var box[] bear_box            = array.new_box()

// FUNCTION TO FIND POTENTIAL FVG BOXES _________________________________________
find_box(t) =>
    var int x = na
    var float _top = na
    var float _bottom = na
    var int _time = na
    if barstate.isconfirmed
        x := low[2] >= high ? -1 : low >= high[2] ? 1 : 0
        _top := x > 0 ? low : x < 0 ? low[2] : 0
        _bottom := x > 0 ? high[2] : x < 0 ? high : 0
        _time := time - t * 60000 * 2
    [_time, _top, _bottom, x]

// FUNCTION TO CREATE BOXES _________________________________________
create_box(_time, _top, _bottom, x, TF) =>
    _col = x > 0 ? BullColor : BearColor
    _extend = extend_r ? extend.right : extend.none
    _text = plotLabel ? (TF + " 𝙁𝙑𝙂") : na
    box boxOB = na
    if x != 0
        boxOB := box.new(left=_time, top=_top, right=last_bar_time + 6, extend=_extend , bottom=_bottom, bgcolor=_col, border_color = na, text=_text, text_halign=text.align_right, text_size=LabelSize, text_color=LabelColor, xloc = xloc.bar_time)
    if x > 0
        array.push(bull_box, boxOB)
    if x < 0
        array.push(bear_box, boxOB)

// FUNCTION TO LIMIT THE NUMBER OF BOXES DISPLAYED _________________________________________
limit_boxes(_boxes) =>
    while array.size(_boxes) > max_boxes
        box.delete(array.shift(_boxes))

// FUNCTION TO CONTROL BOXES (UPDATE OR DELETE) _________________________________________
control_box(_boxes, bearbull) => 
    if array.size(_boxes) > 0
        for i = array.size(_boxes) - 1 to 0 by 1
            _box = array.get(_boxes, i)
            if na(_box)
                array.remove(_boxes, i)
                continue
            _boxLow = box.get_bottom(_box)
            _boxHigh = box.get_top(_box)
            if (bearbull > 0 and low < _boxLow) or (bearbull < 0 and high > _boxHigh)
                box.delete(_box)
                array.set(_boxes, i, na)
            else 
                if bearbull > 0 and low < _boxHigh
                    if changelvl
                        box.set_top(_box, low)
                    if changecolor
                        box.set_bgcolor(_box, BullColorTested)    
                if bearbull < 0 and high > _boxLow
                    if changelvl
                        box.set_bottom(_box, high)
                    if changecolor
                        box.set_bgcolor(_box, BearColorTested)
                box.set_right(_box, last_bar_time + 6)

// FETCH FVG DATA FROM MULTIPLE TIMEFRAMES _________________________________________
[_time1, _top1, _bottom1, xtf1]  = request.security(syminfo.tickerid, tf1, find_box(1))
[_time2, _top2, _bottom2, xtf2]  = request.security(syminfo.tickerid, tf2, find_box(3))
[_time3, _top3, _bottom3, xtf3]  = request.security(syminfo.tickerid, tf3, find_box(5))

// CREATE FVG BOXES IF TIMEFRAME CONDITIONS CHANGE _________________________________________
if timeframe.change(tf1) and show_tf1
    create_box(_time1, _top1, _bottom1, xtf1, tf1)
if timeframe.change(tf2) and show_tf2
    create_box(_time2, _top2, _bottom2, xtf2, tf2)
if timeframe.change(tf3) and show_tf3
    create_box(_time3, _top3, _bottom3, xtf3, tf3)

// CONTROL AND LIMIT FVG BOXES FOR BOTH BULLISH AND BEARISH CONDITIONS _________________________________________
control_box(bull_box, 1)
control_box(bear_box, -1)

// LIMIT THE NUMBER OF DISPLAYED BOXES _________________________________________
limit_boxes(bull_box)
limit_boxes(bear_box)

// PLOT CANDLE _________________________________________
col_border_candle          = color_theme == "𝘿𝘼𝙍𝙆" ? #000000: color_theme == "𝙋𝙐𝙍𝙋𝙇𝙀 𝙂𝙍𝙀𝙀𝙉 𝘿𝘼𝙍𝙆" ? #000000 : #000000
col_candle                 = emaup_trend ? col_bull:col_bear2
col_candle2                = sell_conditions_1 or buy_conditions_1 ? white : white
plotcandle(open,high,low,close,color = show_plot_candle == true ? col_candle : na,wickcolor = show_plot_candle == true ? col_candle : na,bordercolor = show_plot_candle == true ? col_border_candle : na,title = '𝙋𝙇𝙊𝙏 𝘾𝘼𝙉𝘿𝙇𝙀')
